// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvcdczmigjsvrxmiryos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2Y2Rjem1pZ2pzdnJ4bWlyeW9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4OTM4ODQsImV4cCI6MjA2MTQ2OTg4NH0.UUvXPG34rm2TAFJqlGrSJQR6ZFyApChtkp7aldt5Yjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);